apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
spec:
  selector:
    matchLabels:
      service: frontend
  template:
    metadata:
      labels:
        service: frontend
    spec:
      serviceAccountName: nomulus
      containers:
      - name: frontend
        image: gcr.io/GCP_PROJECT/nomulus
        ports:
        - containerPort: 8080
          name: http
        resources:
          requests:
            cpu: "500m"
        args: [ENVIRONMENT]
      - name: proxy
        image: gcr.io/GCP_PROJECT/proxy
        ports:
        - containerPort: 30001
          name: whois
        - containerPort: 30002
          name: epp
        resources:
          requests:
            cpu: "500m"
        args: [--env, ENVIRONMENT, --log, --local]
        env:
        - name: POD_ID
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: NAMESPACE_ID
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: CONTAINER_NAME
          value: proxy
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: frontend
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: frontend
  minReplicas: 1
  maxReplicas: 20
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 100
---
apiVersion: v1
kind: Service
metadata:
  name: frontend
spec:
  selector:
    service: frontend
  ports:
    - port: 80
      targetPort: http
      name: http
    - port: 43
      targetPort: whois
      name: whois
    - port: 700
      targetPort: epp
      name: epp
---
apiVersion: net.gke.io/v1
kind: ServiceExport
metadata:
  name: frontend
