apiVersion: apps/v1
kind: Deployment
metadata:
  name: console
  annotations:
    tag: "latest"
spec:
  selector:
    matchLabels:
      service: console
  template:
    metadata:
      labels:
        service: console
    spec:
      serviceAccountName: nomulus
      containers:
      - name: console
        image: gcr.io/GCP_PROJECT/nomulus
        ports:
        - containerPort: 8080
          name: http
        startupProbe:
          httpGet:
            port: 8080
            path: /ready/console
          initialDelaySeconds: 1
          timeoutSeconds: 60
          successThreshold: 1
          failureThreshold: 3
          periodSeconds: 30
        resources:
          requests:
            # explicit pod-slots 0 is required in order to downgrade node 
            # class from performance, which has implicit pod-slots 1
            cloud.google.com/pod-slots: 0
            cpu: "100m"
            memory: "512Mi"
          limits:
            # explicit pod-slots 0 is required in order to downgrade node 
            # class from performance, which has implicit pod-slots 1
            cloud.google.com/pod-slots: 0
            cpu: "500m"
            memory: "2Gi"
        args: [ENVIRONMENT]
        env:
        - name: POD_ID
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: JETTY_WORKER_INSTANCE
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: NAMESPACE_ID
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: CONTAINER_NAME
          value: console
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: console
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: console
  minReplicas: 1
  maxReplicas: 5
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 100
---
apiVersion: v1
kind: Service
metadata:
  name: console
spec:
  selector:
    service: console
  ports:
    - port: 80
      targetPort: http
      name: http
---
apiVersion: net.gke.io/v1
kind: ServiceExport
metadata:
  name: console
