apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
spec:
  selector:
    matchLabels:
      service: backend
  template:
    metadata:
      labels:
        service: backend
    spec:
      serviceAccountName: nomulus
      containers:
      - name: backend
        image: gcr.io/GCP_PROJECT/nomulus
        ports:
        - containerPort: 8080
          name: http
        resources:
          requests:
            cpu: "500m"
        args: [ENVIRONMENT]
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: backend
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: backend
  minReplicas: 1
  maxReplicas: 20
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 100
---
apiVersion: v1
kind: Service
metadata:
  name: backend
spec:
  selector:
    service: backend
  ports:
    - port: 80
      targetPort: http
      name: http
---
apiVersion: net.gke.io/v1
kind: ServiceExport
metadata:
  name: backend
