# Local development configuration for Nomulus
# This config bypasses authentication and uses local database settings

gcpProject:
  # GCP project configuration for local development
  projectId: newreg-460918
  projectIdNumber: 680343905479
  locationId: us-central1
  isLocal: true
  
  # Service URLs for local development
  defaultServiceUrl: https://newreg-460918.uc.r.appspot.com
  backendServiceUrl: https://backend-dot-newreg-460918.uc.r.appspot.com
  bsaServiceUrl: https://bsa-dot-newreg-460918.uc.r.appspot.com
  toolsServiceUrl: https://tools-dot-newreg-460918.uc.r.appspot.com
  pubapiServiceUrl: https://pubapi-dot-newreg-460918.uc.r.appspot.com
  
  # Base domain for registry services
  baseDomain: registry.tld

gSuite:
  # Registry domain and email configuration
  domainName: registry.tld
  
  # Email configuration
  outgoingEmailDisplayName: TLD Registry
  outgoingEmailAddress: noreply@newreg-460918.appspotmail.com
  newOutgoingEmailAddress: noreply@registry.tld
  replyToEmailAddress: registry@registry.tld
  
  # Admin account configuration
  adminAccountEmailAddress: admin@registry.tld
  supportGroupEmailAddress: support@registry.tld
  consoleUserGroupEmailAddress: users@registry.tld

registryPolicy:
  # Registry branding and identification
  productName: TLD Registry
  contactAndHostRoidSuffix: TLD
  
  # Registry admin registrar
  registryAdminClientId: admin-registrar
  
  # WHOIS and policy configuration
  defaultRegistrarWhoisServer: whois.registry.tld
  greetingServerId: TLD Registry
  
  # TMCH configuration (PILOT for testing environments)
  tmchCaMode: PILOT
  tmchCrlUrl: http://crl.icann.org/tmch_pilot.crl
  tmchMarksDbUrl: https://test-ry.marksdb.org
  
  # Notification settings
  registrarChangesNotificationEmailAddresses:
    - admin@registry.tld

cloudSql:
  # Database configuration for Cloud SQL instance
  jdbcUrl: jdbc:postgresql://google/postgres?cloudSqlInstance=newreg-460918:us-central1:nomulus-db&socketFactory=com.google.cloud.sql.postgres.SocketFactory&useSSL=false
  instanceConnectionName: newreg-460918:us-central1:nomulus-db

auth:
  # OAuth client configuration for console authentication
  oauthClientId: # Will be configured after OAuth setup
  
  # Allowed service account emails for API access
  allowedServiceAccountEmails:
    - newreg-460918@appspot.gserviceaccount.com
    - proxy-service-account@newreg-460918.iam.gserviceaccount.com

beam:
  # Apache Beam (Cloud Dataflow) configuration
  defaultJobRegion: us-central1
  stagingBucketUrl: gs://newreg-460918-snapshots/beam-staging
  initialWorkerCount: 1
  highPerformanceMachineType: n1-highmem-8