name: "Check labels"

on:
  pull_request:
    branches: ["master"]
    types:
      - opened
      - synchronize
      - labeled
      - unlabeled
  merge_group:
    branches: ["master"]
    types: [checks_requested]

jobs:
  fail-by-label:
    runs-on: ubuntu-latest
    steps:
      - name: Fail if PR is labeled as "do not merge"
        if: contains(github.event.pull_request.labels.*.name, 'do not merge')
        run: |
          echo "This PR is labeled as do not merge!"
          exit 1
